# Generated by Django 3.2.7 on 2021-10-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
